FROM debian:bookworm-slim
RUN useradd -m -u 10001 appuser
WORKDIR /app

COPY target/release/tardigrade-worker /usr/local/bin/tardigrade-worker

ENV TARDIGRADE_SERVER_URL=http://tardigrade-server:8080
ENV TARDIGRADE_WORKER_ID=worker-1
USER appuser
CMD ["tardigrade-worker"]
