FROM alpine:3.21
RUN addgroup -g 10001 appgroup \
	&& adduser -D -u 10001 -G appgroup appuser
WORKDIR /app

COPY target/release/tardigrade-worker /usr/local/bin/tardigrade-worker

ENV TARDIGRADE_SERVER_URL=http://tardigrade-server:8080
ENV TARDIGRADE_WORKER_ID=worker-1
USER appuser
CMD ["tardigrade-worker"]
